language:
- cpp

arch:
#- amd64
- arm64
#- ppc64le

os:
- linux
#- osx

dist:
- xenial

osx_image:
- xcode12.5

addons:
  apt:
    packages:
    - ghostscript
    - valgrind
    - groff
  homebrew:
    packages:
    - ghostscript

compiler:
- g++
- clang

script:
- ./autogen.sh
- ./configure
- make
