FROM debian:latest
WORKDIR /opt/vsearch5d
COPY . .
RUN apt-get update
RUN apt-get -y install \
	autoconf \
	automake \
	g++ \
	ghostscript \
	groff \
	libbz2-dev \
	make \
	zlib1g-dev
RUN ./autogen.sh
RUN ./configure CFLAGS="-O2 -fomit-frame-pointer -finline-functions" CXXFLAGS="-O2 -fomit-frame-pointer -finline-functions"
RUN make clean
RUN make ARFLAGS="cr"
RUN make install
ENTRYPOINT ["/usr/local/bin/vsearch5d"]
